app management page
bcgov/mobile-developer-guide pull request #12
Opened 2023-06-30 17:15 UTC by MonicaG

This page describes the permission levels users have in App Store Connect and Google Play Console.

It uses updated info from this [page on the wiki](https://github.com/bcgov/mobile-signing-service/wiki/Google-App-Signing#developer-experience-teams-responsibility) and [this section](https://developer.gov.bc.ca/Mobile-Starter-Kit-Overview#management) on the developer kit

2023-07-12 17:23 UTC, CoffeeGurlNia commented on docs/app_management.md
> +* App Manager
```suggestion

```

2023-07-12 17:23 UTC, CoffeeGurlNia commented on docs/app_management.md
> +* Customer Support
```suggestion

```

2023-07-12 17:23 UTC, CoffeeGurlNia commented on docs/app_management.md
> +* Developer
```suggestion

```

2023-07-12 17:23 UTC, CoffeeGurlNia commented on docs/app_management.md
> +* Marketing
```suggestion

```

2023-07-12 17:23 UTC, CoffeeGurlNia commented on docs/app_management.md
> +* Sales
```suggestion

```

2023-07-12 17:24 UTC, CoffeeGurlNia commented on docs/app_management.md
> +A person may have more than one role. For example, a user may have both the App Manager and Customer Support roles. Please consult Apple's [Program Roles](https://developer.apple.com/support/roles/)
```suggestion

```

2023-07-12 17:25 UTC, CoffeeGurlNia commented on docs/app_management.md
> +
```suggestion
A person may have more than one role. For example, a user may have both the App Manager and Customer Support roles. Please consult Apple's [Program Roles](https://developer.apple.com/support/roles/) documentation for the functions available to each role. The following sections describe the purpose of each role.
```

2023-07-12 17:26 UTC, CoffeeGurlNia commented on docs/app_management.md
> +## Managing User Access To Google Play Console
```suggestion
## Managing user access to Google Play Console
```

2023-07-12 17:26 UTC, CoffeeGurlNia commented on docs/app_management.md
> +[Play Console](https://accounts.google.com/ServiceLogin?service=androiddeveloper&passive=true&continue=https%3A%2F%2Fplay.google.com%2Fconsole%2Fdeveloper%2F&_ga=2.124271306.1978797360.1688067469-933
```suggestion
[Play Console](https://accounts.google.com/ServiceLogin?service=androiddeveloper&passive=true&continue=https%3A%2F%2Fplay.google.com%2Fconsole%2Fdeveloper%2F&_ga=2.124271306.1978797360.1688067469-933612381.1687381212) is the platform that allows teams to manage their apps on the Google Play Store. It uses permission settings to control who has access to do certain functions. The Developer Experience Team will create 3 permission groups for your app:
```

2023-07-12 17:27 UTC, CoffeeGurlNia commented on docs/app_management.md
> +Users will then be assigned into one, or more, or these permission groups.
```suggestion
Users will then be assigned into one, or more, of these permission groups. 
```

2023-07-12 17:43 UTC, CoffeeGurlNia commented on docs/app_management.md
> +Please see the "Permission definitions and uses" section in Google's [Add developer account users and manage permissions]( https://support.google.com/googleplay/android-developer/answer/9844686) docu
```suggestion
See the "Permission definitions and uses" section in Google's [Add developer account users and manage permissions]( https://support.google.com/googleplay/android-developer/answer/9844686) documentation. It provides a complete list of the permissions available.
```

2023-07-12 17:43 UTC, CoffeeGurlNia commented on docs/app_management.md
> +### Admin Permission Group
```suggestion
### Admin permission group
```

2023-07-12 17:44 UTC, CoffeeGurlNia commented on docs/app_management.md
> +### Release Permission Group
```suggestion
### Release permission group
```

2023-07-12 17:47 UTC, CoffeeGurlNia commented on docs/app_management.md
> +The developer experience team will work you to decide which options you would like to enable.
```suggestion
The Developer Experience Team will work with you to decide which options you'd like to enable. 
```

2023-07-12 17:51 UTC, CoffeeGurlNia commented on docs/app_management.md
> +Users in the [Admin Permission Group](#admin-permission-group) can administer this group. This allows them to add or remove users from the group. The Admin Group can also enable or disable the permis
```suggestion
Users in the [admin permission group](#admin-permission-group) can administer this group. This allows them to add or remove users from the group and enable or disable permission options.
```

2023-07-12 17:51 UTC, CoffeeGurlNia commented on docs/app_management.md
> +### Report Permission Group
```suggestion
### Report permission group
```

2023-07-12 17:56 UTC, CoffeeGurlNia commented on docs/app_management.md
> +This permission group lets a user view all information for this app, but not financial data. The permission to view Financial Data can be enabled at the discretion of the Product Owner. Users in the
```suggestion
This permission group lets a user view all information for this app, but not financial data. The permission to view financial data can be enabled at the discretion of the Product Owner. Users in the [admin permission group](#admin-permission-group) for the app can administer this group.
```

2023-07-12 17:56 UTC, CoffeeGurlNia commented on docs/app_management.md
> +### Google Account
```suggestion
### Google account
```

2023-07-12 17:57 UTC, CoffeeGurlNia commented on docs/app_management.md
> +A user does not need a Gmail account in order to make a Google account. Please refer to the "Use an existing email address" section in Google's [Create a Google Account](https://support.google.com/ac
```suggestion
A user doesn't need a Gmail account in order to make a Google account. Refer to the "Use an existing email address" section in Google's [Create a Google Account](https://support.google.com/accounts/answer/27441?hl=en) documentation.
```

2023-07-12 21:52 UTC, MonicaG commented on docs/app_management.md
@CoffeeGurlNia - I reorganized the section a bit. I've moved the section about multiple roles to above the list of roles. I think it should be separate from the Apple ID section

2023-07-14 22:19 UTC, kaitlyn-rosenburg requested changes
finished my edit!

2023-07-14 22:19 UTC, kaitlyn-rosenburg commented on docs/app_management.md
> +[Play Console](https://accounts.google.com/ServiceLogin?service=androiddeveloper&passive=true&continue=https%3A%2F%2Fplay.google.com%2Fconsole%2Fdeveloper%2F&_ga=2.124271306.1978797360.1688067469-933
```suggestion
[Play Console](https://accounts.google.com/ServiceLogin?service=androiddeveloper&passive=true&continue=https%3A%2F%2Fplay.google.com%2Fconsole%2Fdeveloper%2F&_ga=2.124271306.1978797360.1688067469-933612381.1687381212) is the platform that allows teams to manage their apps on the Google Play Store. It uses permission settings to control who has access to do certain functions. The Developer Experience team will create 3 permission groups for your app:
```

2023-07-14 22:19 UTC, kaitlyn-rosenburg commented on docs/app_management.md
> +Users will then be assigned into one, or more, of these permission groups.
```suggestion
Users are then assigned to one or more permission groups. 
```

2023-07-14 22:19 UTC, kaitlyn-rosenburg commented on docs/app_management.md
> +See the "Permission definitions and uses" section in Google's [Add developer account users and manage permissions]( https://support.google.com/googleplay/android-developer/answer/9844686) documentati
```suggestion
Review the "Permission definitions and uses" section in Google's [Add developer account users and manage permissions]( https://support.google.com/googleplay/android-developer/answer/9844686) documentation. It provides a complete list of the permissions available.
```

2023-07-14 22:19 UTC, kaitlyn-rosenburg commented on docs/app_management.md
> +See the "Permission definitions and uses" section in Google's [Add developer account users and manage permissions]( https://support.google.com/googleplay/android-developer/answer/9844686) documentati
don't use "see" as it implies the reader is a sighted person

2023-07-14 22:19 UTC, kaitlyn-rosenburg commented on docs/app_management.md
> +The permissions available to this group include the following:
```suggestion
The permissions available to this group include:
```

2023-07-14 22:19 UTC, kaitlyn-rosenburg commented on docs/app_management.md
> +The Developer Experience Team will work with you to decide which options you'd like to enable.
```suggestion
The Developer Experience team will work with you to decide which options you'd like to enable. 
```

2023-07-14 22:19 UTC, kaitlyn-rosenburg commented on docs/app_management.md
> +This permission group lets a user view all information for this app, but not financial data. The permission to view financial data can be enabled at the discretion of the Product Owner. Users in the
```suggestion
This permission group lets a user view all information for this app (except financial data). The permission to view financial data can be enabled at the discretion of the Product Owner. Users in the [admin permission group](#admin-permission-group) for the app can administer this group.
```

2023-07-14 22:19 UTC, kaitlyn-rosenburg commented on docs/app_management.md
> +A user doesn't need a Gmail account in order to make a Google account. Refer to the "Use an existing email address" section in Google's [Create a Google Account](https://support.google.com/accounts/a
```suggestion
A user doesn't need a Gmail account in order to make a Google account. Review to the "Use an existing email address" section in Google's [Create a Google Account](https://support.google.com/accounts/answer/27441?hl=en) documentation.
```

2023-07-17 15:26 UTC, MonicaG commented
@kaitlyn-rosenburg - Thank you for your review! I've committed the changes you suggested. You can [review them here](https://github.com/bcgov/mobile-developer-guide/pull/12/commits/8244bb853066663aeb827bd2f1589e75de2b9c4a).  I've also updated ['Role' to 'role' for all of the headings](https://github.com/bcgov/mobile-developer-guide/pull/12/commits/9448048e640b45691ab149961309063766604581).

2023-07-19 21:18 UTC, kaitlyn-rosenburg approved these changes

2023-07-20 15:15 UTC, merged