google app signing
bcgov/mobile-developer-guide pull request #14
Opened 2023-07-05 21:44 UTC by MonicaG

This source for this page is from [Google App Signing](https://github.com/bcgov/mobile-signing-service/wiki/Google-App-Signing) document. I removed references about the Developer Experience Team responsibilities. This guide is focused only on developers. Internal documentation to the Developer Experience Team will be handled separately

2023-07-16 20:24 UTC, kaitlyn-rosenburg requested changes

2023-07-16 20:24 UTC, kaitlyn-rosenburg commented on docs/google_app_signing.md
> +# Google Signing
```suggestion
# Google app signing
```

2023-07-16 20:24 UTC, kaitlyn-rosenburg commented on docs/google_app_signing.md
> +To learn about code signing, please review Google's [Sign your app](https://developer.android.com/studio/publish/app-signing) documentation.
```suggestion
To learn about code signing, review Google's [Sign your app](https://developer.android.com/studio/publish/app-signing) documentation.
```

2023-07-16 20:24 UTC, kaitlyn-rosenburg commented on docs/google_app_signing.md
> +This guide describes how an app team should work with Google keys. You must use the Province of BC's Google Play developer account to distribute your app.
move up to be intro sentence of page

2023-07-16 20:24 UTC, kaitlyn-rosenburg commented on docs/google_app_signing.md
> +React Native apps need extra setup to use the keys. Please see the [React Native Signing Guide](google_react_native_signing.md) for more details.
```suggestion
React Native apps need extra setup to use the keys. Review the [React Native Signing Guide](google_react_native_signing.md) for more details.
```

2023-07-16 20:24 UTC, kaitlyn-rosenburg commented on docs/google_app_signing.md
> +- upload key
```suggestion
- Upload key
```

2023-07-16 20:24 UTC, kaitlyn-rosenburg commented on docs/google_app_signing.md
> +- app signing key
```suggestion
- App signing key 
```

2023-07-16 20:24 UTC, kaitlyn-rosenburg commented on docs/google_app_signing.md
> +Please refer to Google's [Play App Signing](https://developer.android.com/studio/publish/app-signing#app-signing-google-play) documentation for an in-depth review of the two keys.
```suggestion
Use Google's [Play App Signing](https://developer.android.com/studio/publish/app-signing#app-signing-google-play) documentation for an in-depth review of the two keys.
```

2023-07-16 20:24 UTC, kaitlyn-rosenburg commented on docs/google_app_signing.md
> +If your app's code is in the [bcgov GitHub organization](https://github.com/bcgov), then please use a [GitHub Action](https://docs.github.com/en/actions) to build and sign your app with the upload ke
```suggestion
If your app's code is in the [bcgov GitHub organization](https://github.com/bcgov), use a [GitHub Action](https://docs.github.com/en/actions) to build and sign your app with the upload key. 

Refer to Google's [Sign your app from command line](https://developer.android.com/build/building-cmdline#sign_cmdline) documentation for instructions on how to do this. Store the key ([encoded as base64](https://docs.github.com/en/actions/security-guides/encrypted-secrets#storing-base64-binary-blobs-as-secrets)), its alias and the password as a [secret](https://docs.github.com/en/actions/security-guides/encrypted-secrets) in your app's repo. 
```

2023-07-16 20:24 UTC, kaitlyn-rosenburg commented on docs/google_app_signing.md
> +See the [bc-wallet-mobile](https://github.com/bcgov/bc-wallet-mobile/blob/main/.github/workflows/main.yaml) project for an example of a project using GitHub Actions.
```suggestion
The [bc-wallet-mobile](https://github.com/bcgov/bc-wallet-mobile/blob/main/.github/workflows/main.yaml) project is a good example of a project using GitHub Actions.
```

2023-07-16 20:24 UTC, kaitlyn-rosenburg commented on docs/google_app_signing.md
> +If you are using a different git host, then please see its documentation on how to create a CI/CD pipeline. Use its secret feature to store the key and password securely.
```suggestion
If you're using a different git host, review its documentation on how to create a CI/CD pipeline. Use its secret feature to store the key and password securely.
```

2023-07-16 20:24 UTC, kaitlyn-rosenburg commented on docs/google_app_signing.md
> +If you do not use a CI/CD pipeline, then store the key and password somewhere securely.  However, we encourage teams to use a CI/CD pipeline. It provides repeatable builds and safely stores the crede
```suggestion
If you don't use a CI/CD pipeline, store the key and password somewhere securely. 
We encourage teams to use a CI/CD pipeline. It provides repeatable builds and safely stores the credentials.
```

2023-07-16 20:24 UTC, kaitlyn-rosenburg commented on docs/google_app_signing.md
> +Please use the [Play App Signing](https://developer.android.com/studio/publish/app-signing#app-signing-google-play) service to sign your app. If you do not use this service and you lose your app’s si
```suggestion
Use the [Play App Signing](https://developer.android.com/studio/publish/app-signing#app-signing-google-play) service to sign your app. If you don't use this service and you lose your app’s signing key, you lose the ability to update your app. Google's [Using Play App Signing](https://developer.android.com/studio/publish/app-signing#enroll) documentation describes how to setup it up for your app.
```

2023-07-17 15:43 UTC, MonicaG commented on docs/google_app_signing.md
> +To learn about code signing, please review Google's [Sign your app](https://developer.android.com/studio/publish/app-signing) documentation.
```suggestion
This guide describes how an app team should work with Google keys. You must use the Province of BC's Google Play developer account to distribute your app.

To learn about code signing, review Google's [Sign your app](https://developer.android.com/studio/publish/app-signing) documentation.
```

2023-07-17 15:43 UTC, MonicaG commented on docs/google_app_signing.md
> +This guide describes how an app team should work with Google keys. You must use the Province of BC's Google Play developer account to distribute your app.
```suggestion

```

2023-07-17 15:53 UTC, MonicaG commented
@kaitlyn-rosenburg - I've applied the suggestions you requested. You can [review them here](https://github.com/bcgov/mobile-developer-guide/pull/14/commits/46c28bef7cc16137b11f6230ee266f9ff4e51d28?diff=split&w=0#diff-d824c3986b12eee9403daa846c2f02a2bf8be78cfb520b4da0d229721ad955e2).

2023-07-19 21:10 UTC, kaitlyn-rosenburg approved these changes

2023-07-20 15:16 UTC, merged